### ISSUE TITLE
Support for Pipeline and Transaction in python

### ISSUE THREAD

**Issue by reubenjohn** [upstash/redis-py#45]
The typescript client supports these commands: [https://upstash.com/docs/oss/sdks/ts/redis/commands/transaction](https://upstash.com/docs/oss/sdks/ts/redis/commands/transaction). Curious to know if these will be available in the Python SDK any time soon?

## Pipeline Typescript SDK Usage 
```typescript
const p = redis.pipeline()
p.set('foo', 'bar')
p.get('foo')
const res = await p.exec()
```
## Transaction Typescript SDK Usage
```typescript
const tx = redis.multi()
tx.set('foo', 'bar')
tx.get('foo')
const res = await tx.exec()
```

**Comment by mmangus** [comment]
+1 to this request, pipelining is absolutely indispensable for using redis over the internet in my opinion. i hacked together pipelining for my org by subclassing the client to add a method that uses the `_session`, `_url` and `_headers` to send commands to the `/pipeline` REST endpoint, but would much prefer to have proper support built into the SDK e.g. a context manager `with redis.pipeline() as pipe: ...`.

**Comment by coratype** [comment]
any updates on this?

**Comment by CahidArda** [comment]
Hi again, we added pipelines and transactions as of [version 1.1.0](https://github.com/upstash/redis-py/releases/tag/v1.1.0)!

Closing this issue.
